export type T_ACTIONS_TRACKING = typeof ACTIONS_TRACKING;

export const ACTIONS_TRACKING = {
  ADD_NEW_TRACK: 'ADD_NEW_TRACK',
  SET_CURRENT_TRACK: 'SET_CURRENT_TRACK',
  SET_CURRENT_TIME_TRACK: 'SET_CURRENT_TIME_TRACK',
  IN_TRACKING: 'IN_TRACKING'
} as const;
